/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hb.struts.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 05-29-2016
 * 
 * XDoclet definition:
 * @struts.form name="loginHeadForm"
 */
public class LoginHeadForm extends ActionForm {
	
	private String name;
	private FormFile myphoto;
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public FormFile getMyphoto() {
		return myphoto;
	}
	public void setMyphoto(FormFile myphoto) {
		this.myphoto = myphoto;
	}
	
	
}