/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hb.struts.action;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.UUID;

import javax.jws.soap.SOAPBinding.Use;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.hb.domain.User;
import com.hb.services.UserService;
import com.hb.struts.form.LoginHeadForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-29-2016
 * 
 * XDoclet definition:
 * @struts.action
 */
public class UpandLoadAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		LoginHeadForm elementForm = (LoginHeadForm)form;
		String name=elementForm.getName();
		FormFile file = elementForm.getMyphoto();
		String filenameString = file.getFileName();
		
		//使用UUID处理文件名。
		int beginindex = filenameString.lastIndexOf(".");
		String uuid = UUID.randomUUID().toString();
		
		String uuidname = uuid+filenameString.substring(beginindex,filenameString.length());
		
		int size = file.getFileSize();
		
		InputStream inputStream = null;
		OutputStream outputStream = null;
		
		try {
			inputStream = file.getInputStream();
			//得到file文件夹的绝对路径
			String path = this.getServlet().getServletContext().getRealPath("/picture");
			outputStream = new FileOutputStream(path+"\\"+uuidname);
			
			//开始上传
			int len = 0;
			byte[] bytes = new byte[1024];
			while((len = inputStream.read(bytes))>0){
				outputStream.write(bytes,0,len);
			}
			
			UserService userService = new UserService();
			User user = new User();
			user.setName(name);
			user.setGoalfilename(uuidname);
			user.setSourcefilename(filenameString);
			if (!userService.saveRegisterUsers(user)) {
				
				return mapping.findForward("err");
			}
			
		} catch (Exception e) {
			// TODO: handle exception
		}finally{
			try {
				inputStream.close();
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			try {
				outputStream.close();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		
		return mapping.findForward("success");
	}
}













